### ISSUE TITLE
Comment style needs to change

### ISSUE THREAD

**Issue by jeffturcotte** [imarc/boilerplate-archived#1]
We really just need a better css comment standard across the board. Right now sections are something like this:

```
/* == section ====================================== */
```

But this is cleaner and more manageable:

```
/* section */
```

I never want to have to copy a comment from elsewhere, or count a certain number of characters to make a new comment.

**Comment by khamer** [comment]
For VIM: I/\* <c-o>73a=<esc>a */

Just kidding. @marcelmoreau seems to like and promote block style comments through CSS, and we've used them on the past few sites. I don't have anything against them. Don't ask me why I made mine 79 characters long (counting through the slashes) instead of 80, I don't know and don't have any preference.

If we were going to ditch them, I'd probably be in favor of 'markdown' like ones like

``` css
/* = Top Level = */
...
/* == Second Level == */
...
/* === Third Level === */
...
```

But, to be honest, I think the visibility of the block style comments is better.

**Comment by jeffturcotte** [comment]
I'm not totally opposed to the =, ==, ===.

Still, the visibility argument is overrated. Personally, I think it makes more sense to just order the selectors alphabetically (also Elements, IDs, then Classes). but I know nobody will agree with me there.

**Comment by marcelmoreau** [comment]
Yeah you will not with the alphabetical selectors argument.

I like obnoxious comment blocks because they are a visual aid for me. Jeff, your section denotations look the same as a comment someone might write. I can quickly scroll through a document and see where a new section begins – I map a new section like this to the CSS's table of contents. 

I also vote to always **alphabetize the properties** in our CSS declarations:

``` css

/* --------------------------------------------------------- */
/* structure
/* --------------------------------------------------------- */

.widget {
    background-color: #666;
    height: auto;
    left: 4px;
    position absolute;
    top: 20px;
    width: 960px;
}
```

**Comment by khamer** [comment]
Alphabetizing properties per selector (other than browser prefixes, which should immediately, alphabetically proceed the property) sounds good and is easy to implement and remember. So,

``` css
.widget {
    background-color: #666;
    -moz-box-sizing: border-box;
    -ms-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    height: auto;
    left: 4px;
    position absolute;
    top: 20px;
    width: 960px;
}
```

For example.

 The one line "block" was my compromise between the three line blocks you have Marcel and something shorter, but as I said, no preference.
